### ISSUE TITLE
Logging to Windows Event Log using manifest

### ISSUE THREAD

**Issue by Hydra820** [microsoft/Detours#100]
Hello,
I'm using Microsoft Detours for an api logging project of mine, specifically trcapi.
I'm also using Syelog to check the output and I want to create an event log so I could forward them.
I looked around the web and it seems I need to create a manifest, has anyone done something similar for trcapi?

Thanks in advance.

**Comment by bgianfo** [comment]
Closing this given it's a question, an answer was provided and it's inactive.
Feel free to re-open the issue if you want to discuss things further.
