### ISSUE TITLE
About UWP app limitations

### ISSUE THREAD

**Issue by ArmsOfSorrow** [microsoft/Detours#103]
I've read the [point in the FAQ](https://github.com/Microsoft/Detours/wiki/FAQ#why-cant-my-windows-store-app-for-windows-10-include-detours) which outlines why Detours is not supported in UWP apps.

However, upon looking at the [allowed APIs list](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis) for UWP apps, the ones listed as examples are either allowed or have a potentially equivalent replacement:
- `FlushInstructionCache` is allowed, see [here](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-core-processthreads-l1-1-1dll)
- `VirtualAlloc`/`VirtualProtect` have [VirtualAllocFromApp](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualallocfromapp)/[VirtualProtectFromApp ](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualprotectfromapp) variations which look fit for the purpose

Can anyone clarify this a bit further? No criticism intended, I'm just trying to learn. :)

**Comment by sylveon** [comment]
Detour uses VirtualAllocEx, ReadProcessMemory and WriteProcessMemory to manipulate a third party process. Those APIs are not available under UWP.

**Comment by bgianfo** [comment]
Looks like @sylveon answered this question, I'm going to close this issue for now.
Feel free to re-open if you have further questions on the matter.
