### ISSUE TITLE
Can I use Detours on WinCE ?

### ISSUE THREAD

**Issue by yanzixiang** [microsoft/Detours#106]
And how ?

**Comment by sylveon** [comment]
Have you tried building it with the WinCE SDK? Currently this targets Windows XP and only uses kernel32 APIs so I'd expect it to work without much trouble.

**Comment by yanzixiang** [comment]
> Have you tried building it with the WinCE SDK? Currently this targets Windows XP and only uses kernel32 APIs so I'd expect it to work without much trouble.

I have NOT .
Because there is NOT an sln that I can use to do this ,
I do NOT know how to use an WinCE SDK to build this into an detours.lib ,
Can u give me some kind of help ?

**Comment by yanzixiang** [comment]
https://github.com/microsoft/Detours/blob/64ec135a509884aa60ac6c19b59564f1da9cb2fa/src/detours.h#L840

My WinCE SDK does NOT have this file,
Can this be disabled by some option ?

**Comment by bgianfo** [comment]
> My WinCE SDK does NOT have this file,
> Can this be disabled by some option ?

Does WinCE SDK include `imagehelp.h`? I don't have any experience using it, but it looks like there is support for downlevel compilers using the imaghlp.h header instead. Maybe that could also be used on WinCE? 

```cpp
//////////////////////////////////////////////////////////////////////////////
//
#if (_MSC_VER < 1299)
#include <imagehlp.h>
typedef IMAGEHLP_MODULE IMAGEHLP_MODULE64;
typedef PIMAGEHLP_MODULE PIMAGEHLP_MODULE64;
typedef IMAGEHLP_SYMBOL SYMBOL_INFO;
typedef PIMAGEHLP_SYMBOL PSYMBOL_INFO;

static inline
LONG InterlockedCompareExchange(_Inout_ LONG *ptr, _In_ LONG nval, _In_ LONG oval)
{
    return (LONG)::InterlockedCompareExchange((PVOID*)ptr, (PVOID)nval, (PVOID)oval);
}
#else
#pragma warning(push)
#pragma warning(disable:4091) // empty typedef
#include <dbghelp.h>
#pragma warning(pop)
#endif
```

**Comment by bgianfo** [comment]
I'm going to close this issue just because of the how long it's been sitting in active, feel free to re-open in case you have further questions.

**Comment by yanzixiang** [comment]
> > My WinCE SDK does NOT have this file,
> > Can this be disabled by some option ?
> 
> I think the `dbghelp.h` API's are only needed to support [DetourFindFunction](https://github.com/microsoft/Detours/wiki/DetourFindFunction), unless I missed something in the code. Looking at the [API's available in windows CE](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee488416(v=winembedded.60)) it looks like it doesn't have support. If you don't need `DetourFindFunction` support then you might be able to rip it out and get the other pieces compiling and working.
> 
> I assume you are targeting a x86 / ARM 32 ISA, and not MIPS / PowerPC / SuperH (not support)?
> It looks like Windows CE is a derivative of NT, so it appears to have all the critical API's that detours depends on, so it doesn't seem out of the real of possibility that it might work without too much effort once you get it building.

without DetourFindFunction,
how to fint the address of the function ?

**Comment by sylveon** [comment]
You can use GetProcAddress
