### ISSUE TITLE
Get class ID of ActiveX/COM object app is loading in traceapi sample

### ISSUE THREAD

**Issue by Tronmech** [microsoft/Detours#110]
I'm using the traceAPI sample to see how/if I can get what I need for detours. I have an application crashing in an "unloaded" .ocx file. ("Legacy Code for 100, Alex") In Process Monitor, I can see the ocx get opened, memory mapped with CreateFileMapping() and read.  I'm reasonably sure my application isn't unloading the ocx, and not unloading it or decrementing the refcount atthe wrong time... Mostly because this legacy app only breaks when run in a specific Citrix version. This means I need to argue with Citrix that it ain't my company's fault...

Unless I'm mistaken, which is likely 1000% the case, the "REFCLSID rclsid," in CoGetClassObject() and CoCreateInstance is eventually the GUID for the object... So, this SHOULD work:
```
        HRESULT rv = 0;
	HRESULT stringrv = 0;
	LPOLESTR classid = NULL;
	stringrv=StringFromCLSID(a0,&classid);
	if (stringrv != S_OK) {
		_PrintEnter("CoGetClassObject(%p,%p,%p,%p,%p)\n", a0, a1, a2, a3, a4);
	}
	else {
		_PrintEnter("CoGetClassObject(%p (%s),%p,%p,%p,%p)\n", a0, classid, a1, a2, a3, a4);
	}
```

I get SOMETHING back, but it doesn't look anything like a class ID from HKCR\TypeLib or CLSID... 
`20200716130830096 1320 50.60: trcapi32: 001   +CoGetClassObject(3050f406 (-11CF98B5-),aa0082bb,bcebd00,8346488,1)`

So, I'm obviously doing SOMETHING wrong, but I'll be darned if I understand what...

**Comment by bgianfo** [comment]
Closing this issue,  feel free to reopen if you want to discuss further. Thanks!
