### ISSUE TITLE
DetourCreateProcessWithDllW will crash exe when dll not have export function

### ISSUE THREAD

**Issue by wzwangyike** [microsoft/Detours#120]
My inject dll not have any export function, and I use DetourCreateProcessWithDllW Or DetourCreateProcessWithDllExW to inject this dll to exe(notepad.exe), and the exe can not run. when I export a function, the exe run ok.

**Comment by bgianfo** [comment]
This is intentional, see the "Remarks" section of the documentation for that API in the wiki:
https://github.com/microsoft/Detours/wiki/DetourCreateProcessWithDll#remarks

> Note: The new process will fail to start if the detour DLL does not export DetourFinishHelperProcess as export ordinal #1.

**Comment by wzwangyike** [comment]
I sorry, I didn't see the wiki.
I have a problem, why not have a API, just DetourCreateProcessWithDllEx have 32bit dll and 64bit dll。
because without process start, I can not know create process is 32bit or 64bit.

**Comment by bgianfo** [comment]
Can you provide more details?
I'm not following what problem you are trying to solve and what API is missing to help you achieve that.

**Comment by wzwangyike** [comment]
Sorry, my English is not very good

Currently, the provided API can only inject specific DLLs, such as 32-bit or 64 bit

But until the target process starts, I don't know whether the target process is 32-bit or 64 bit.

It can provide an API with two parameters: 32-bit DLL directory and 64 bit DLL directory

In this way, the API selects which DLL to inject according to the target process
