### ISSUE TITLE
detours skip "DLL_PROCESS_DETACH" event in the dll

### ISSUE THREAD

**Issue by luca2125** [microsoft/Detours#125]
Hi,

I use this code to hook a sound function of a game exe:

	AddressOfHookFunction = Scanner.FindPattern(SC::To_Char(ExeFileName), "\x55\x8B\xEC\x51\x83\x3D\x94\x55\x91", "xxxxxxxxx"); // BattleZoneRedux 43AA30

		DetourTransactionBegin();
		DetourUpdateThread(GetCurrentThread());

		// this will hook the function
		DetourAttach(&(LPVOID&)AddressOfHookFunction, &HookSoundFile);

this code work. But when I use it, the dll event "DLL_PROCESS_DETACH" will never trigger. If I remove this Detours code. the event DLL_PROCESS_DETACH will call normally.

The event 'DLL_PROCESS_DETACH' is important for me. There is a way to solve the problem ?

Apart this, can you confirm if Detours 4.1 work on 64 bit ? If yes I need only to compile it to x64 ? or need more steps ?

Thanks !

**Comment by bgianfo** [comment]
> But when I use it, the dll event "DLL_PROCESS_DETACH" will never trigger. If I remove this Detours code. the event 
> DLL_PROCESS_DETACH will call normally.
> 
> The event 'DLL_PROCESS_DETACH' is important for me. There is a way to solve the problem ?

The `DLL_PROCESS_DETACH` never triggered for what dll?
Can you provide a stand alone repro of the issue to help us understand?
It's hard to know what's going  on with so few details. 

> Apart this, can you confirm if Detours 4.1 work on 64 bit ? If yes I need only to compile it to x64 ? or need more steps?

Yes, Detours works on 64 bit, if you only  want to use x64 then you only need to compile x64.

**Comment by luca2125** [comment]
hi bgianfo,

You have right excuse me.

I attach the file dllmain.cpp
[dllmain.zip](https://github.com/microsoft/Detours/files/5134786/dllmain.zip)

I explain with more details, I have created a dll (d3d9.dll) to put inside a game to add the force feedback support becouse the game don't support it.

The dll work, but when my dll call detours, the event "DLL_PROCESS_DETACH'" will not call.

If I remove detours, the event "DLL_PROCESS_DETACH'" will call normally.

So seem that detours don't allow to trigger this event that in my case is important.

Can you help me please ?

Thanks !

**Comment by bgianfo** [comment]
Thanks for the additional details @luca2125.

## Background + Testing
I tried to repro the bug by writing a test using one of the existing samples which detours in DllMain (this is one of the main usages of Detours).

Here's the diff, you can see we just LoadLibrary the dll, then FreeLibrary to get DllMain to get executed with `DLL_PROCESS_ATTACH` and then `DLL_PROCESS_DETACH`

```diff
diff --git a/samples/simple/Makefile b/samples/simple/Makefile
index 1597519..f7adf1f 100644
--- a/samples/simple/Makefile
+++ b/samples/simple/Makefile
@@ -16,6 +16,7 @@ LIBS=$(LIBS) kernel32.lib
 all: dirs \
     $(BIND)\simple$(DETOURS_BITS).dll \
     $(BIND)\sleep5.exe \
+    $(BIND)\detach-test.exe \
     \
 !IF $(DETOURS_SOURCE_BROWSING)==1
     $(OBJD)\simple$(DETOURS_BITS).bsc \
@@ -52,6 +53,13 @@ $(BIND)\sleep5.exe : $(OBJD)\sleep5.obj $(DEPS)
         /link $(LINKFLAGS) $(LIBS) \
         /subsystem:console

+$(OBJD)\detach-test.obj : detach-test.cpp
+
+$(BIND)\detach-test.exe : $(OBJD)\detach-test.obj $(DEPS)
+    cl $(CFLAGS) /Fe$@ /Fd$(@R).pdb $(OBJD)\detach-test.obj \
+        /link $(LINKFLAGS) $(LIBS) \
+        /subsystem:console
+
 $(OBJD)\sleep5.bsc : $(OBJD)\sleep5.obj
     bscmake /v /n /o $@ $(OBJD)\sleep5.sbr

@@ -61,6 +69,7 @@ clean:
     -del *~ 2>nul
     -del $(BIND)\simple*.* 2>nul
     -del $(BIND)\sleep5.* 2>nul
+    -del $(BIND)\detach-test.* 2>nul
     -rmdir /q /s $(OBJD) 2>nul

 realclean: clean
diff --git a/samples/simple/detach-test.cpp b/samples/simple/detach-test.cpp
new file mode 100644
index 0000000..4914af0
--- /dev/null
+++ b/samples/simple/detach-test.cpp
@@ -0,0 +1,19 @@
+#include <stdio.h>
+#include <windows.h>
+#include <detours.h>
+
+int __cdecl main(int argc, char ** argv)
+{
+    (void)argc;
+    (void)argv;
+
+    for (DWORD counter = 0; counter < 5; ++counter) {
+        HMODULE detours = LoadLibraryW(L"simple" DETOURS_STRINGIFY(DETOURS_BITS) ".dll");
+
+        Sleep(10*counter);
+
+        FreeLibrary(detours);
+    }
+
+    return 0;
+}
```

The existing sample looks pretty similar to the code you have in the code sample you shared, it just detours a single function on attach and removes the detour on detach: 
https://github.com/microsoft/Detours/blob/a9e6186a8838a6c9671db3b07d3c449e41262347/samples/simple/simple.cpp#L41-L71

We can see the test works as designed: 

```
C:\src\detours> bin.X64\detach-test.exe
simple64.dll: Starting.
simple64.dll: Detoured SleepEx().
simple64.dll: Removed SleepEx() (result=0), slept 0 ticks.
simple64.dll: Starting.
simple64.dll: Detoured SleepEx().
simple64.dll: Removed SleepEx() (result=0), slept 16 ticks.
simple64.dll: Starting.
simple64.dll: Detoured SleepEx().
simple64.dll: Removed SleepEx() (result=0), slept 16 ticks.
simple64.dll: Starting.
simple64.dll: Detoured SleepEx().
simple64.dll: Removed SleepEx() (result=0), slept 31 ticks.
simple64.dll: Starting.
simple64.dll: Detoured SleepEx().
simple64.dll: Removed SleepEx() (result=0), slept 47 ticks.
```

# Conclusion 

I think that something else must be going on with the code that happens to be on the path you are calling detours with.
Here's some idea's that might help:
-  I noticed in the sample you provided you execute some external code that wasn't provided, but looking at the signature it looked like it might call LoadLibrary (Scanner::FindPattern mentioned in your original report). LoadLibrary is one of the specific things you should never do inside DllMain (see reference [Dynamic-Link Library Best Practices](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices)) perhaps this is causing some weird dependency loop? 

- Is it possible there are extra calls to LoadLibrary for your DLL? That would cause an outstanding reference count on the module and thus it wouldn't be unloaded until process unload? You can use "Application Verifier" to trace load library calls, and then use the [!avrf](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-avrf) windbg extension to dump them.
 

      0:000> !avrf -dlls 1
      Dumping last 1 entries from tracker @ 00000125e6b91fc0 with 53 valid entries ...
      --------------------------------------------------------------
      LoadLibrary: Thread ID: 24B8, Base address: 00007ffcb8ad0000, Name: simple64.dll
      00007ffcb2777980: vfbasics!AVrfpLdrLoadDll+0xB0
      00007ffd19261f90: KERNELBASE!LoadLibraryExW+0x150
      00007ffcb2701c69: vfprint!VfLoadLibraryW+0x29
      00007ff77c431035: detach_test!main+0x35
      00007ff77c43123c: detach_test!__scrt_common_main_seh+0x10C
      00007ffd1a5330f4: KERNEL32!BaseThreadInitThunk+0x14
      00007ffd1bb7dceb: ntdll!RtlUserThreadStart+0x2B

**Comment by luca2125** [comment]
hi bgianfo,

You must excuse me, I have already solved the problem.

Now each time that unload the dll the event DLL_PROCESS_DETACH will always call.

This library work good as I expected.

If possible I need your suggest if possible:

I have some strange issue in c++ with DirectInput Microsot library.

What is the best way to contact microsoft for c++ DirectInput support ?

Many thanks for your support.

**Comment by bgianfo** [comment]
> You must excuse me, I have already solved the problem.
> 
> Now each time that unload the dll the event DLL_PROCESS_DETACH will always call.
> 
> This library work good as I expected.

Great, glad it's working for you!

>If possible I need your suggest if possible:
>
> I have some strange issue in c++ with DirectInput Microsot library.
> 
> What is the best way to contact microsoft for c++ DirectInput support ?

Looking at the README of the [Direct X Samples](https://github.com/microsoft/DirectX-Graphics-Samples) repo, it looks like the DirectX folks have a discord server that you could use to get help. See: https://discord.com/invite/directx

I don't know of a better way than that.

Good luck!
