### ISSUE TITLE
Project Upgrade Failed.

### ISSUE THREAD

**Issue by lambdagit101** [microsoft/Detours#147]
**Describe the bug**
I try to open system.mak, and I get this
![wersolution](https://user-images.githubusercontent.com/48295237/96100083-a217e100-0edc-11eb-8684-26aa99b89ea4.PNG)

and if I press OK,
![projectupgradefailed](https://user-images.githubusercontent.com/48295237/96100108-a93eef00-0edc-11eb-9b02-7ecc5e2bba35.PNG)

**Expected behavior**
I tried it in Visual Studio 2017. I tried it in Visual Studio 2019. I even tried it in Code::Blocks. CodeBlocks cannot open the file, and both versions I specified give me the same error.

**Additional context**
Nothing else.

**Comment by sylveon** [comment]
Just open it as folder in VS and then use the CLI to build with nmake.

**Comment by lambdagit101** [comment]
Thank you. This solved the issue
