### ISSUE TITLE
How i can hook global openprocess api?

### ISSUE THREAD

**Issue by czxichen** [microsoft/Detours#148]
`#include "pch.h"
#include "pp.h"
#include <windows.h>
#include <fstream> 
#include "include/detours.h"
#ifndef _WIN64
#pragma comment(lib, "lib.X64/detours.lib")
#else 
#pragma comment(lib, "lib.X86/detours.lib")
#endif

typedef HANDLE(WINAPI* pfOpenProcess)(DWORD dwDesiredAccess, BOOL  bInheritHandle, DWORD dwProcessId);
pfOpenProcess oldOpenProcess; 

HANDLE hookOpenProcess(DWORD dwDesiredAccess, BOOL  bInheritHandle, DWORD dwProcessId)
{
    SetLastError(5);
    return NULL; 
}

void Hook()
{
    DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread()); 
    DetourAttach((PVOID*)&oldOpenProcess, hookOpenProcess);
    DetourTransactionCommit();
}

void UnHook()
{
    DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread()); 
    DetourDetach((PVOID*)&oldOpenProcess, hookOpenProcess);
    DetourTransactionCommit();
}

BOOL APIENTRY DllMain(_In_ void* _DllHandle, _In_ unsigned long _Reason, _In_opt_ void* _Reserved)
{
    if (_Reason == DLL_PROCESS_ATTACH)
    {
        oldOpenProcess = (pfOpenProcess)DetourFindFunction("Kernel32.dll", "OpenProcess");
        Hook();
    }
    else if (_Reason == DLL_PROCESS_DETACH)
    {
        UnHook();
    }
    return TRUE;
}`

This method is only valid for the current process, how to work global

**Comment by sylveon** [comment]
You can't globally hook without either injecting to every process or writing a kernel filter driver

**Comment by czxichen** [comment]
> You can't globally hook without either injecting to every process or writing a kernel filter driver

Ok,Thanks
