### ISSUE TITLE
How to hook an existing local process?

### ISSUE THREAD

**Issue by 0xThiebaut** [microsoft/Detours#162]
I am looking to hook an existing local process but can't find any clear documentation on how to do so.

I have tried, without success:
- Using `CreateToolhelp32Snapshot` to iterate threads followed by `OpenThread` to call `DetourUpdateThread`.
- Using `OpenProcess` to call `DetourUpdateProcessWithDll`.

I checked #76 but feel the suggested approach is for the process itself. Is their any documentation on how Detours can be used for an existing local process?

**Comment by sylveon** [comment]
You will need to inject a DLL into the target process and can then use DetourUpdateThread.

A few ways you can inject a DLL is by using SetWindowsHookEx, SetWinEventHook, or CreateRemoteThread + LoadLibrary.

**Comment by 0xThiebaut** [comment]
I went with `CreateRemoteThread` + `LoadLibraryA`. Thanks!
