### ISSUE TITLE
does this library work for x64 ?

### ISSUE THREAD

**Issue by alexa872** [microsoft/Detours#169]
hay everyone, i haven't try to build it yet, but does this library supports x64 architectures ? ill be trying to hook createprocess() and NtOpenFile() and OpenProcess() .
im not worried for the last 2 functions but i had problems hooking createprocess() using different libraries, and thats why i am here.
and is there examples or documentations on this library?
thank you for your time and have a nice day

**Comment by sylveon** [comment]
Yes. There are samples in the samples folders and the wiki holds API documentation

**Comment by bgianfo** [comment]
> Yes. There are samples in the samples folders and the wiki holds API documentation

Yup, please see: 
- [Detouring 32-bit and 64-bit Processes](https://github.com/microsoft/Detours/wiki/OverviewHelpers)
- [Samples](https://github.com/microsoft/Detours/wiki/Samples)

**Comment by alexa872** [comment]
> > Yes. There are samples in the samples folders and the wiki holds API documentation
> 
> Yup, please see:
> 
> * [Detouring 32-bit and 64-bit Processes](https://github.com/microsoft/Detours/wiki/OverviewHelpers)
> * [Samples](https://github.com/microsoft/Detours/wiki/Samples)

thank you for your reply

**Comment by bgianfo** [comment]
Closing this out at your question appears to have been resolved.
