### ISSUE TITLE
AntiVirus Scan - FalsePositive

### ISSUE THREAD

**Issue by DerEnderman** [microsoft/Detours#174]
I startet compile it on my machine but i got an Warning by some detection engines.

https://www.virustotal.com/gui/file/8ae0fb24684f44560ccd9a8b970d0f6ef290c75d8253761162dccb6e3293b628/detection

Can you confirm this?

**Comment by bgianfo** [comment]
AV's are most likely detecting the function hooking code in Detours and assuming it's a virus / malware.
There's certainly no malware intentionally checked into the repo.

**Comment by dtarditi** [comment]
We recommend that you exclude the directory where you compiling Detours from anti-virus scanning.

**Comment by bgianfo** [comment]
Closing this out.
