### ISSUE TITLE
Build warning Problem

### ISSUE THREAD

**Issue by rchildre3** [microsoft/Detours#186]
**Describe the bug**
Type mismatch in `FindPayloadInRemoteDetourSection`:
```
~/detours/creatwth.cpp: In function ‘void* FindPayloadInRemoteDetourSection(HANDLE, const GUID&, DWORD*, PVOID)’:
~/detours/creatwth.cpp:194:20: warning: converting to non-pointer type ‘DWORD’ {aka ‘long unsigned int’} from NULL [-Wconversion-null]
  194 |         *pcbData = NULL;
      |                    ^~~~
```

Should the assignment be to 0 since `*pcbData`  is not a pointer type?

**Expected behavior**
Builds without warnings

**Detours version**
https://github.com/microsoft/Detours/commit/827b89608ce66892963d1467d15a86f0b2832a78

**Comment by bgianfo** [comment]
Thanks for the bug report @rchildre3

**Comment by rchildre3** [comment]
Sure thing there quite a few more with `-Wreorder` and `-Wsign-compare` are those worth of an issue ass well?

**Comment by sylveon** [comment]
Good catch! Fixing this right away

**Comment by bgianfo** [comment]
> @bgianfo Sure thing. There quite a few more with `-Wreorder` and `-Wsign-compare` are those worthy of an issue as well?

If you are willing to file them, we are willing to look and triage them.
