### ISSUE TITLE
#error:  Unknown architecture (x86, amd64, ia64, arm, arm64)

### ISSUE THREAD

**Issue by sin90-Lab** [Microsoft/Detours#19]
hello 
I got this error but can`t find how to handle this

I also tried different status like,
Win 10 64bit VS 2017,VS 2015, VS 2012
Win 7 64bit VS 2015, VS 2012
Win 7 32bit VS 2015, VS 2012

but have same problem

I would appreciate it if you could help this problem

With Regards

**Comment by sharowyeh** [comment]
You may need to describe more details about how to represent the issue or post your repro steps.
If error occurred at your project included detours.h, you should check the platform target at project's configuration.
If you just want to build the source code,  I prefer opening native tools command prompt from windows start menu then trying nmake command.

**Comment by Arefu** [comment]
Have you opened the x64 developer console as referenced in my issue: https://github.com/Microsoft/Detours/issues/5

Have you installed the C++ project deps in Vs2017?

**Comment by Krzysztow** [comment]
Is it during compilation of your program, which includes `detours.h`? You might want to include "Windows.h" before the other include.

**Comment by dtarditi** [comment]
This looks like it is resolved.
