### ISSUE TITLE
Hooking multi thread applications

### ISSUE THREAD

**Issue by djn3m0** [microsoft/Detours#199]
Hi,

Im new to Microsoft detours, in provided sample codes I only see that we are hooking the current thread,

```
DetourUpdateThread(GetCurrentThread());
DetourAttach(...);
```

Is this mean that if other threads in the application want to call the function we are hooking they will not call the hooked function?

Thanks

**Comment by sylveon** [comment]
They will call the hooked function, but there is a risk they try to do so while the hook is being installed. You should enumerate all threads in the process and then call DetourUpdateThread for each one.

**Comment by djn3m0** [comment]
So I will try to inject normally if I ran into any undefined behavior then I will take snapshot, pause all threads, call `DetourUpdateThread()` on each of them.

But just to make sure, by doing,

```
DetourUpdateThread(GetCurrentThread());
DetourAttach(...);
```
All the threads in the process will be calling the hooked function, without any extra work? Even with the fact that we call `DetourUpdateThread` on the current thread?

Thanks

**Comment by sylveon** [comment]
Yes, the change is global

**Comment by djn3m0** [comment]
Thanks for the quick response. That helped a lot.
