### ISSUE TITLE
Feature request: Add support for PDB files

### ISSUE THREAD

**Issue by CaledoniaProject** [microsoft/Detours#203]
I need to hook non-exported methods with detours. The symbol name is available in PDB files, can you add support for that?

**Comment by sylveon** [comment]
You can use the DIA SDK to find the RVA of the non-exported method and then derive the real address to pass to DetourAttach from the HMODULE, Detours doesn't need special support for this.

**Comment by CaledoniaProject** [comment]
Ah, Make sense.
