### ISSUE TITLE
Hooking by sequence of bytes

### ISSUE THREAD

**Issue by uniql0** [microsoft/Detours#204]
Hi,

Is it possible to hook a function when we only have a signature of that function in sequence of bytes?

Thanks

**Comment by bgianfo** [comment]
Unfortunately, no, there is no support for such functionality currently. 

You would have to discover the address of the function on your own, and then you could call [`DetourAttach(...)`](https://github.com/microsoft/Detours/wiki/DetourAttach) / [`DetourAttachEx(...)`](https://github.com/microsoft/Detours/wiki/DetourAttachEx) with that address.

**Comment by bgianfo** [comment]
Closing this... feel free to re-open if you have follow up questions.
