### ISSUE TITLE
Question: How do I compile Detours for v141_xp?

### ISSUE THREAD

**Issue by akineechan** [microsoft/Detours#205]
I've been struggling to what I need to set for Detours to compile as v141_xp. Could someone tell me what to set?

\- aki

**Comment by bgianfo** [comment]
> I've been struggling to what I need to set for Detours to compile as v141_xp.

Can you share your repro steps and what errors are encountering?

**Comment by akineechan** [comment]
I'm not getting any errors? I was asking how i compile it for v141_xp. I ended up changing the if statement for DETOURS_WIN_7 for it to always compile with /D_USING_V110_SDK71_ and that worked out great
