### ISSUE TITLE
Missing function 'detour_find_jmp_bounds' for ARM64 build

### ISSUE THREAD

**Issue by unknownv2** [Microsoft/Detours#21]
Building for ARM64 gives the error:
```
error C3861: 'detour_find_jmp_bounds': identifier not found"
```

The function seems defined for all of the other platforms (x86, x64, IA64, ARM) except for ARM64. The *detour_find_jmp_bounds* function is called by *detour_alloc_trampoline* when calling *DetourAttachEx*.

The call is at: https://github.com/Microsoft/Detours/blob/master/src/detours.cpp#L1163

**Comment by Ocasio-J** [comment]
Resolution? I am getting this error.

**Comment by Ocasio-J** [comment]
Woops. I was using the source code from releases which is a bit outdated.
