### ISSUE TITLE
Hook WIN11: NtCreateUserProcess hook not enter!

### ISSUE THREAD

**Issue by wzwangyike** [microsoft/Detours#219]
**Describe the bug**
i hooked NtCreateUserProcess at win11 explorer.exe. when i doudle click file to open. it not enter this API hook.(like notepad)  
i use promon to look the stack. it will call ZwCreateUserProcess,it same as early windows system.  
but i use my explorer addin to createprocess. it will enter hook API. it looks hook is ok, but some thread cannot hook it ?

**Comment by bgianfo** [comment]
Did you figure it out? 😄

**Comment by wzwangyike** [comment]
> Did you figure it out? 😄
en..it's RPC call, not in explorer to createprocess. but the parent is set to explorer.
