### ISSUE TITLE
vcpkg

### ISSUE THREAD

**Issue by NN---** [Microsoft/Detours#22]
Add Detours to vcpkg

**Comment by dtarditi** [comment]
As https://github.com/Microsoft/vcpkg/issues/3794 says,  you could submit a PR to vcpkg for this.

**Comment by sylveon** [comment]
I've done so here: https://github.com/Microsoft/vcpkg/pull/5347

**Comment by sylveon** [comment]
It's been merged, this issue can now be closed.

**Comment by dtarditi** [comment]
Thanks!
