### ISSUE TITLE
Can this detect when a external process creates (with CreateRemoteThread), suspends, and terminates threads?

### ISSUE THREAD

**Issue by CatGirlsAreLife** [Microsoft/Detours#25]
I been working on a library that does just this, however it seems my current inplementation (a thread count system) seems to crash. Although it could be the loaded dll's check too since sometimes the dll's it finds gets some really jumbled up file names and paths despite running through GetModuleFileNameA/W (I do not remember if I am using the Unicode one or not as I provide A and W options of my library functions too).

Basically I want this sort of check to where it returns some values indicating from my library that someone is modifying the process externally and allow the process to handle the closing, possible report the user to a server in case of them trying to hack a game with some hack tool or w/e.

All my other functions work perfectly fine. Also I tend to keep this library closed source, although I do not have any sort of version control on it which is stupid in case of hdd crash. I *should* store it in a private GitLab or bitbucket repository :thinking:.

I want to know this so that way I can get the idea why the thread stuff seems to not work.

**Comment by dtarditi** [comment]
Detours can be used to intercept calls to functions within a process.  I don't think it'd be suitable for detecting when an external process is modifying threads within a process.

**Comment by CatGirlsAreLife** [comment]
Aww darn I wish there was a way even if it is registering some event or hook that gets called at the lowest part of the windows threading implementation (including the handle of the process that called ´´CreateRemoteThread´´ of the type returned from ´´GetCurrentProcess´´.
