### ISSUE TITLE
Is possible to trace all WINAPI calls a process does?

### ISSUE THREAD

**Issue by R3uan3** [microsoft/Detours#252]
For example, if you would need to listen to each `WM_MESSAGE` a process is receiving you could put a hook on `GetMessage`  or in her `DefWindowProc`.

Is it possible to hook something similar in which I could see each `WINAPI` the process is calling?

**Comment by bgianfo** [comment]
That's the goal of the [traceapi](https://github.com/microsoft/Detours/wiki/SampleTraceapi) sample.
It attaches to all the known WIN32 APIs, ~1400 when it was last updated, and traces the function call and return value.

It's not possible (AFAIK) to at runtime enumerate all `WINAPI` functions and dynamically attach though, it has to be a static known set at compile time.

**Comment by R3uan3** [comment]
I see, for each API i hook even if it does 'nothing' it increases the process or system CPU usage?

**Comment by bgianfo** [comment]
If it never gets called, then the only additional time will be spent at startup / shutdown when you attach and detach the hook. If the hook is never called there should be no other impact.

**Comment by sylveon** [comment]
There are dedicated tools for this, like Rohitab API Monitor: http://www.rohitab.com/apimonitor

**Comment by R3uan3** [comment]
I'm already using this tool :)
thank you guys
