### ISSUE TITLE
detours.h error Unknown architecture (x86, amd64, ia64, arm, arm64)

### ISSUE THREAD

**Issue by liph1988** [Microsoft/Detours#29]
when I include detours.h, report Unknown architecture (x86, amd64, ia64, arm, arm64) when compile.
after I add 
#define _X86_ 
the compile report so many error
>d:\detours\include\detours.h(267): error C2061: 语法错误: 标识符“DWORD”
1>d:\detours\include\detours.h(268): error C2061: 语法错误: 标识符“Data2”
1>d:\detours\include\detours.h(268): error C2059: 语法错误:“;”
1>d:\detours\include\detours.h(269): error C2061: 语法错误: 标识符“Data3”
1>d:\detours\include\detours.h(269): error C2059: 语法错误:“;”
1>d:\detours\include\detours.h(270): error C2061: 语法错误: 标识符“Data4”
1>d:\detours\include\detours.h(270): error C2059: 语法错误:“;”
1>d:\detours\include\detours.h(270): error C2059: 语法错误:“[”
1>d:\detours\include\detours.h(271): error C2059: 语法错误:“}”
1>d:\detours\include\detours.h(312): error C2061: 语法错误: 标识符“DETOUR_EXE_RESTORE_GUID”
1>d:\detours\include\detours.h(312): error C2059: 语法错误:“;”
...................
but the detours/sample are compiled ok.i do not know why~
I use win7 VS2017

I would appreciate it if you could help this problem

With Regards

**Comment by sharowyeh** [comment]
It can not be defined platform target at that way, checks the C/C++->Preprocessor->Preprocessor Definition or Linker->Advanced->Target Machine in the project configuration properties, hopes help :)

**Comment by liph1988** [comment]
@sharowyeh thanks
I am sorry,I only find Configuration properties->C/C++->Preprocessor->Preprocessor Definition
![image](https://github.com/liph1988/smarthome/blob/master/doc/vs01.png).I can't find Advanced->Target Machine.

**Comment by sharowyeh** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/machine-specify-target-platform

**Comment by liph1988** [comment]
@sharowyeh The value of Linker->Advanced->Target Machine is MachineX86 (/MACHINE:X86).The error is reported during compiling,not linking.I'm confused~

**Comment by liph1988** [comment]
I am so stupid.I include "detours.h" before include<Windows.h>.Change their order will ok.thanks very much, sharowyeh.

**Comment by sharowyeh** [comment]
Glad you solved it. :)

Basically VS has different macros of preprocessor definition included platform architecture (x86/amd64/etc), changed automatically by selected platform target from project properties or build/debug configuration.
It also affects definitions of loaded library and the library references, changed by manually or make define in somewhere is not recommended, from my experiences.
