### ISSUE TITLE
Does detours need huge extra memory? 

### ISSUE THREAD

**Issue by jizhideyu** [Microsoft/Detours#33]
I use **DetourCreateProcessWithDll** to create my app process and find the process use **1.6g** memory in win task-manager view. Normally, my app use **0.8g** memory in win task-manager view. 
It's confuse that i can only catch the **0.8g** memory using (by hooking **NtAllocateVirtualMemory** and **VirtualAlloc** ) when use **DetourCreateProcessWithDll**.
I want to know what's the problem?

**Comment by dstd** [comment]
@jizhideyu if you use sucha formatting to force everybody to give up reading your message looks like you achieved your goal..

**Comment by jizhideyu** [comment]
@dstd I'm sorry. I have edited my comment.

**Comment by Arefu** [comment]
Not an expert by any means, but would this have something to do with it?

> After the detour DLL has been loaded, it should reverse changes to the in-memory import table by calling DetourRestoreAfterWith. To facilitate reversing these changes, DetourCreateProcessWithDll copies relevant reversal data into a payload in the target process using the DetourCopyPayloadToProcess API. The loaded DLL should call the DetourRestoreAfterWith API to restores the contents of the import table.
