### ISSUE TITLE
2.1 or 3.0 professional version vs 4.0.1 version

### ISSUE THREAD

**Issue by asukun** [Microsoft/Detours#35]
The Customers - who purchased 2.1 or 3.0 professional version - should use 4.0.1(MIT Lincense) version for updating?

professional version(commercial version) will not be released anymore?

**Comment by dtarditi** [comment]
Yes, you should use tje 4.0.1 (MIT license) version.    It has the same functionality as the professional version.  We do not plan to release updates to the professional version.
