### ISSUE TITLE
Distribute Detours on NuGet

### ISSUE THREAD

**Issue by sylveon** [Microsoft/Detours#37]
Distributing Detours on NuGet would make acquiring, updating and using it much easier than storing third-party binaries and headers in our GitHub repository.

**Comment by dtarditi** [comment]
We don't plan to do this.  Detours is a statically-linked library that should be linked into your C/C++ application.  It is simple enough to compile the library from sources.   Detours used to be distributed as a DLL, but we no longer distribute it that way.
