### ISSUE TITLE
Can't Seem To Make x64?

### ISSUE THREAD

**Issue by Arefu** [Microsoft/Detours#5]
Hey Peeps,

I have VS2017 installed latest updates with the C++ tools installed.
I might be missing dependencies however when I open up the Developer Command Prompt and make the project it compiles fine for x86. I did try make all and it certainly tries but when it gets to x64 it seems to error out on: 
`iping_d.obj : error LNK2001: unresolved external symbol _iping_ProxyFileInfo`
Would I be able to get any advice on this why it pops up when making for x64 and not x86 or am I being so stupid I'm not seeing what is wrong.

**Comment by NoMoreFood** [comment]
This is literally all I ever do to build it:

```
SET DETOURS_TARGET_PROCESSOR=X64
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
NMAKE
```

**Comment by Arefu** [comment]
I may be stupid then, I'll try this when I wake up in the morning

**Comment by NoMoreFood** [comment]
Possibly but I wouldn't think so for this basic compiling and linking.  Possibly a different SDK version.  Did you try from a clean, unzipped copy of the Detours source?  I've had issue when building the x64 libraries in the same directory I've used for x86.  You can also do 'nmake clean'. 

One side note: if it's getting as far as linking the example binaries, the core library files are already built -- and that's really what most people need.

**Comment by Arefu** [comment]
Yes, I downloaded it fresh when you commented on my laptop which has Win10 1803 on it, C++ tools and all, I don't know what's going on, I'll try it at work and see if we have access to Enterprise licences and try again.

**Comment by Arefu** [comment]
Installed Enterprise, same issue. I might install XP support it could be something stupid like that knowing how MS sometimes works ;), if not I'll report back even more confused.

For reference what do you have installed for VS?

**Comment by NoMoreFood** [comment]
I just have the '.NET desktop development' and 'Desktop development with C++' workloads installed.

**Comment by Arefu** [comment]
Then I'm out of ideas, I've got the same but doesn't work for me.

**Comment by RomanKhv** [comment]
The same problem: setting DETOURS_TARGET_PROCESSOR=x64 just puts binaries in x64 folder but the .lib file seems to be created by x86 compiler
When I try to use it I get
1>k:\Detours\Detours-master\lib.X64\detours.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'

**Comment by dtarditi** [comment]
VS2017 comes with several command shell prompts.  The default one `Developer Command Prompt for VS2017` invokes the x86-targeting compiler.   Try using the `x64 Native Tools Command Prompt for VS2017` shell instead.   This should invoke the x64-targeting compiler.   I'm assuming that you have a 64-bit version of Windows installed.  If not, you'll need to use the `x86_64 Cross Tools Command Prompt for VS2017`.

Each VC++ compiler binary only supports one target, so you have to make sure that you are invoking the right one.  This is different than clang, for example, which is built as a cross-compiler that supports multiple target architectures.

The error message from the pastebin log shows that the wrong compiler is being invoked:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.EXE
```
At the end of path `HostX86` means that the compiler is hosted on x86.   The following subdirectory `x86` means that the compiler is targeting x86 too.

**Comment by Arefu** [comment]
Oh I feel stupid, I didn't even see that in the error message. 

That solved it. Thank you!
