### ISSUE TITLE
Why do not provide VS2017 solution file?

### ISSUE THREAD

**Issue by stang2019** [microsoft/Detours#65]
Is there any plan to provide VS2017 solution file?

**Comment by stang2019** [comment]
The reason I asked this because I tried to compile it with the nmake, it will ask windows.h header file, I add its path into env, then nmake keep asking other depends header files, there are many include subfolders in Win10 SDK, I'm not supposed to add all of them in the include env.
If you guys provide a VS2017 or even old VS2015 project or solution file, that will make people's life much easier.
Thanks

**Comment by sylveon** [comment]
If you run nmake from within a Visual Studio developer command prompt it should build.

**Comment by stang2019** [comment]
It won't, I have VS2017 Pro installed, I don't have problem in compiling VS2017 sln Win32/Win64 project, when compiling from prompt of vsvars32, it keeps ask me to add dependencies include into the environments, there are many subfolders of Win10 SDK includings, I couldn't add all of them into INCLUDE system env.

**Comment by dtarditi** [comment]
We have no plans to add a VS2017 project file.
