### ISSUE TITLE
Update wiki with new information for debugging

### ISSUE THREAD

**Issue by Lectem** [microsoft/Detours#69]
Hi,
I am unsure how to contribute to the wiki since I do not have write access to it, but here is a suggestion for improvement of the [FAQ](https://github.com/microsoft/Detours/wiki/FAQ) page.

In the [How can I debug the startup of my detour DLL?](https://github.com/microsoft/Detours/wiki/FAQ#how-can-i-debug-the-startup-of-my-detour-dll) it only mentions Windbg, it is however possible to use Visual Studio too.

I suggest adding the following paragraph at the end.

> It is also possible to debug child processes in Visual Studio by using the [Microsoft Child Process Debugging Power Tool](https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool) official extension.

**Comment by bgianfo** [comment]
I've gone ahead and added the relevant information to the wiki.
The wiki revision can be seen [here](https://github.com/microsoft/Detours/wiki/FAQ/_compare/139873adafd78771f847af4ff4c2937f49b1704b).

Thanks for the suggestion! 👍
