### ISSUE TITLE
I don't understand the content of “disasm.cpp”, especially these flags and macro definitions, what are they used for?  

### ISSUE THREAD

**Issue by TonyHaircut** [microsoft/Detours#71]
// nFlagBits flags.                 
    enum {
        DYNAMIC     = 0x1u,
        ADDRESS     = 0x2u,
        NOENLARGE   = 0x4u,
        RAX         = 0x8u,
    };

    // ModR/M Flags
    enum {
        SIB         = 0x10u,
        RIP         = 0x20u,
        NOTSIB      = 0x0fu,
    };
    ...
    #define ENTRY_CopyBytes1Dynamic     1, 1, 0, 0, DYNAMIC, &CDetourDis::CopyBytes
    #define ENTRY_CopyBytes2            2, 2, 0, 0, 0, &CDetourDis::CopyBytes
    #define ENTRY_CopyBytes2Jump        ENTRY_DataIgnored &CDetourDis::CopyBytesJump
    #define ENTRY_CopyBytes2CantJump    2, 2, 0, 1, NOENLARGE, &CDetourDis::CopyBytes
    #define ENTRY_CopyBytes2Dynamic     2, 2, 0, 0, DYNAMIC, &CDetourDis::CopyBytes
    #define ENTRY_CopyBytes3            3, 3, 0, 0, 0, &CDetourDis::CopyBytes
    #define ENTRY_CopyBytes3Dynamic     3, 3, 0, 0, DYNAMIC, &CDetourDis::CopyBytes
    #define ENTRY_CopyBytes3Or5         5, 3, 0, 0, 0, &CDetourDis::CopyBytes
    ...

**Comment by bgianfo** [comment]
The flags and macros are used to build disassembly tables to aide in decoding a stream of bytes into the individual machine instructions encoded within.

If you are interested in studying how x86 instructions are encoded/decoded, I would recommend you read the [X86-64 Instruction Encoding](https://wiki.osdev.org/X86-64_Instruction_Encoding) article for a nice introduction. The article will help you understand some of the terminology as well as methodologies used in disasm.cpp. For example the SIB flag that is used in the code is described here: https://wiki.osdev.org/X86-64_Instruction_Encoding#SIB

The `Intel 64 and IA-32 Architectures Software Developer's Manuals` document instruction encoding in great detail: https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html

**Comment by bgianfo** [comment]
I'm going to close this question out as it's inactive, feel free to re-open if you want to resume the discussion.
