### ISSUE TITLE
member.exe is detected as Trojan:Win32/Skeeyah.A!MTB by Windows Defender

### ISSUE THREAD

**Issue by fsmv** [microsoft/Detours#73]
Here it is in VirusTotal https://www.virustotal.com/gui/file/255d34ac5786570b9066e325cb8bb2bac34411650ebfbac0906d315c516d3397/summary

Some users of the Vortex mod manager program are discussing this problem here https://forums.nexusmods.com/index.php?/topic/7873523-vortex-v10-only-trojan-virus-in-memberexe/

The program is using a version of the exe built by this project https://github.com/Nexus-Mods/node-native-errors/blob/master/build_detours.js

The path to the file is .\Vortex\resources\app.asar.unpacked\node_modules\native-errors\Detours\bin.X64\member.exe

The download link for this program is here https://www.nexusmods.com/site/mods/1?tab=files

**Comment by dtarditi** [comment]
This is outside the scope of the Detours projects.
