### ISSUE TITLE
Missing DetourFindPayloadEx documentation

### ISSUE THREAD

**Issue by sylveon** [microsoft/Detours#77]
There is no documentation in the wiki for the DetourFindPayloadEx API.

**Comment by bgianfo** [comment]
I've added docs for DetourFindPayLoadEx, here: 

- https://github.com/microsoft/Detours/wiki/DetourFindPayloadEx
- https://github.com/microsoft/Detours/wiki/Reference/_compare/b029f51b6dc8a1687cf7abe4e34f83e91fcf2a3d

Thank you for filing the issue and letting us know!
We appreciate it.
