### ISSUE TITLE
DetourCreateProcessWithDllsW with LPCWSTR dll names

### ISSUE THREAD

**Issue by mwetzko** [microsoft/Detours#82]
Hello Detours Team,

currently, it is not possible to call DetourCreateProcessWithDllsW with wide character dll names, because DetourCreateProcessWithDllsW uses LPCSTR and StringCchLengthA to count the dll name length. Please change the _DetourCreateProcessWithDlls**W**_, so that it can consume wide chars for dll names respectively.

Thank you!

https://github.com/microsoft/Detours/blob/edc8b07ae7e7325d9b9d551b46122a82665161b8/src/creatwth.cpp#L1505

**Comment by YellowAfterlife** [comment]
I think it comes down to UPDATE_IMPORTS_XX in `uimports.cpp`. Unfortunately, I do not know enough of process structure to guess what you would need to do with this for it to work with wide LPCWSTRs.

In my case I currently just copy the DLL to the target directory if needed, though have also considered using `subst`.

**Comment by sonyps5201314** [comment]
use LPCSTR is because createwth.cpp use IAT to inject your dlls to destination process， so the imported dll name items must be ANSI version string，so it is not a problem.

**Comment by bgianfo** [comment]
Closing this as won't fix, as @sonyps5201314's explanation is correct. There's not much we can do here.
