### ISSUE TITLE
Sniffing a serial port

### ISSUE THREAD

**Issue by tohn21** [microsoft/Detours#93]
I need to monitor another process serial port read-write to open and close, may I ask what I need to do?

**Comment by yanzixiang** [comment]
What u need is a software called AccessPort,
Which can monitor all serial port operations.

**Comment by morsisko** [comment]
It depends how the read-write operation is done. Generally you can treat serial port like a file and some apps actually do that. If that is the case the app can write/read to/from it using `WriteFile` or `ReadFile` and you can use this library to api hook those functions, or use any other monitoring software like `ApiMonitor` or `Process Monitor` from SysInternals.

**Comment by dtarditi** [comment]
The question has been answered.
